-- Hi Care Supabase schema
-- PostgreSQL / Supabase
--
-- This schema mirrors the current Hi Care application tables:
--   users
--   hicare_admin_accounts
--   hicare_condition_statuses
--   hicare_condition_audits
--   hicare_activity_logs
--
-- Authentication note:
-- The current application uses its own email/password session cookie. The
-- auth_user_id column is included so the database can be migrated to Supabase
-- Auth without losing the existing member records. Once Supabase Auth is used,
-- set users.auth_user_id = auth.users.id for each member. The Supabase
-- service_role key bypasses RLS and must only be used on the server.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Shared trigger helper
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- Members
-- -----------------------------------------------------------------------------

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  -- Existing Hi Care local identifier. Example: local_<uuid>.
  open_id varchar(64) not null unique,
  -- Optional future link to Supabase Auth.
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text,
  email varchar(320),
  login_method varchar(64) default 'local',
  -- Current application stores scrypt output as 128 hex characters and the
  -- random salt as 32 hex characters. Keep both nullable for Supabase Auth rows.
  password_hash varchar(128),
  password_salt varchar(32),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now(),
  constraint users_local_credentials_check check (
    (login_method = 'local' and password_hash is not null and password_salt is not null)
    or login_method is distinct from 'local'
    or (password_hash is null and password_salt is null)
  )
);

create unique index if not exists users_email_lower_unique
  on public.users (lower(email))
  where email is not null;

create index if not exists users_created_at_idx on public.users (created_at desc);
create index if not exists users_last_signed_in_idx on public.users (last_signed_in desc);

 drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Legacy/custom Hi Care administrator account
-- -----------------------------------------------------------------------------

create table if not exists public.hicare_admin_accounts (
  id smallint primary key check (id = 1),
  email varchar(320) not null,
  password_hash varchar(128) not null,
  salt varchar(32) not null,
  created_at timestamptz not null
);

create unique index if not exists hicare_admin_accounts_email_lower_unique
  on public.hicare_admin_accounts (lower(email));

-- -----------------------------------------------------------------------------
-- Disease-card availability
-- -----------------------------------------------------------------------------

create table if not exists public.hicare_condition_statuses (
  condition_id varchar(64) primary key,
  is_active boolean not null default true,
  notice varchar(160) not null default '',
  open_date date,
  updated_at timestamptz
);

create index if not exists hicare_condition_statuses_active_idx
  on public.hicare_condition_statuses (is_active);

insert into public.hicare_condition_statuses (condition_id, is_active, notice)
values
  ('hypertension', true, ''),
  ('diabetes', true, ''),
  ('dyslipidemia', true, ''),
  ('liver', true, ''),
  ('ckd', true, ''),
  ('tuberculosis', true, ''),
  ('obesity', true, ''),
  ('heart', true, '')
on conflict (condition_id) do nothing;

-- -----------------------------------------------------------------------------
-- Admin change history
-- -----------------------------------------------------------------------------

create table if not exists public.hicare_condition_audits (
  id uuid primary key default gen_random_uuid(),
  condition_id varchar(64) not null,
  admin_email varchar(320) not null,
  action varchar(16) not null check (action in ('activate', 'schedule')),
  is_active boolean not null,
  notice varchar(160) not null default '',
  open_date date,
  changed_at timestamptz not null default now()
);

create index if not exists hicare_condition_audits_time_idx
  on public.hicare_condition_audits (changed_at desc);
create index if not exists hicare_condition_audits_condition_idx
  on public.hicare_condition_audits (condition_id, changed_at desc);

-- -----------------------------------------------------------------------------
-- Employee activity logs
-- -----------------------------------------------------------------------------

create table if not exists public.hicare_activity_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  event_type varchar(64) not null check (event_type in ('page_visit', 'condition_open', 'guide_open')),
  condition_id varchar(64),
  keyword_id varchar(128),
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hicare_activity_logs_user_time_idx
  on public.hicare_activity_logs (user_id, created_at desc);
create index if not exists hicare_activity_logs_time_idx
  on public.hicare_activity_logs (created_at desc);
create index if not exists hicare_activity_logs_condition_idx
  on public.hicare_activity_logs (condition_id, created_at desc);

-- -----------------------------------------------------------------------------
-- RLS helper functions
-- -----------------------------------------------------------------------------

-- SECURITY DEFINER prevents the admin check from recursively evaluating the
-- users SELECT policy. Keep search_path locked to trusted schemas.
create or replace function public.is_hicare_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.users u
    where u.auth_user_id = auth.uid()
      and u.role = 'admin'
  );
$$;

create or replace function public.current_hicare_user_id()
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select u.id
  from public.users u
  where u.auth_user_id = auth.uid()
  limit 1;
$$;

revoke all on function public.is_hicare_admin() from public;
grant execute on function public.is_hicare_admin() to authenticated, service_role;
revoke all on function public.current_hicare_user_id() from public;
grant execute on function public.current_hicare_user_id() to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Enable RLS
-- -----------------------------------------------------------------------------

alter table public.users enable row level security;
alter table public.hicare_admin_accounts enable row level security;
alter table public.hicare_condition_statuses enable row level security;
alter table public.hicare_condition_audits enable row level security;
alter table public.hicare_activity_logs enable row level security;

-- Members: a member sees their own profile; an admin sees all member records.
drop policy if exists users_select_self_or_admin on public.users;
create policy users_select_self_or_admin
on public.users for select
to authenticated
using (auth_user_id = auth.uid() or public.is_hicare_admin());

drop policy if exists users_insert_self on public.users;
create policy users_insert_self
on public.users for insert
to authenticated
with check (auth_user_id = auth.uid() or public.is_hicare_admin());

drop policy if exists users_update_self_or_admin on public.users;
create policy users_update_self_or_admin
on public.users for update
to authenticated
using (auth_user_id = auth.uid() or public.is_hicare_admin())
with check (auth_user_id = auth.uid() or public.is_hicare_admin());

drop policy if exists users_delete_admin_only on public.users;
create policy users_delete_admin_only
on public.users for delete
to authenticated
using (public.is_hicare_admin());

-- The legacy admin credential table is never readable by ordinary members.
drop policy if exists admin_accounts_admin_only on public.hicare_admin_accounts;
create policy admin_accounts_admin_only
on public.hicare_admin_accounts for all
to authenticated
using (public.is_hicare_admin())
with check (public.is_hicare_admin());

-- Disease availability is public read; only an authenticated Hi Care admin can edit.
drop policy if exists condition_statuses_public_read on public.hicare_condition_statuses;
create policy condition_statuses_public_read
on public.hicare_condition_statuses for select
to anon, authenticated
using (true);

drop policy if exists condition_statuses_admin_write on public.hicare_condition_statuses;
create policy condition_statuses_admin_write
on public.hicare_condition_statuses for all
to authenticated
using (public.is_hicare_admin())
with check (public.is_hicare_admin());

-- Admin audit history is private to admins.
drop policy if exists condition_audits_admin_only on public.hicare_condition_audits;
create policy condition_audits_admin_only
on public.hicare_condition_audits for all
to authenticated
using (public.is_hicare_admin())
with check (public.is_hicare_admin());

-- Activity logs: members can create/read only their own records; admins can
-- read and manage all records. The current server should use service_role for
-- inserts if it continues to use its own signed session cookie.
drop policy if exists activity_logs_select_self_or_admin on public.hicare_activity_logs;
create policy activity_logs_select_self_or_admin
on public.hicare_activity_logs for select
to authenticated
using (user_id = public.current_hicare_user_id() or public.is_hicare_admin());

drop policy if exists activity_logs_insert_self_or_admin on public.hicare_activity_logs;
create policy activity_logs_insert_self_or_admin
on public.hicare_activity_logs for insert
to authenticated
with check (user_id = public.current_hicare_user_id() or public.is_hicare_admin());

drop policy if exists activity_logs_update_admin_only on public.hicare_activity_logs;
create policy activity_logs_update_admin_only
on public.hicare_activity_logs for update
to authenticated
using (public.is_hicare_admin())
with check (public.is_hicare_admin());

drop policy if exists activity_logs_delete_admin_only on public.hicare_activity_logs;
create policy activity_logs_delete_admin_only
on public.hicare_activity_logs for delete
to authenticated
using (public.is_hicare_admin());

-- -----------------------------------------------------------------------------
-- Grants for Supabase client roles
-- -----------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;
grant select on public.hicare_condition_statuses to anon, authenticated;
grant select, insert, update, delete on public.users to authenticated;
grant select, insert, update, delete on public.hicare_admin_accounts to authenticated;
grant select, insert, update, delete on public.hicare_condition_statuses to authenticated;
grant select, insert, update, delete on public.hicare_condition_audits to authenticated;
grant select, insert, update, delete on public.hicare_activity_logs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- Optional convenience view for Admin dashboards. RLS on the base tables still
-- applies to the view when queried by authenticated users.
create or replace view public.hicare_activity_report
with (security_invoker = true)
as
select
  l.id,
  l.user_id,
  u.name,
  u.email,
  l.event_type,
  l.condition_id,
  l.keyword_id,
  l.metadata,
  l.created_at
from public.hicare_activity_logs l
left join public.users u on u.id = l.user_id;

grant select on public.hicare_activity_report to authenticated;
