import React, { useEffect, useState } from "react";
import { ArrowLeft, Download, FileSpreadsheet, RefreshCw, Trash2 } from "lucide-react";
import { SURVEY_STORAGE_KEY, SurveyResponse } from "./Survey";

const headers = ["제출일시", "질환", "이름/식별명", "관리 상태", "가장 어려운 점", "선호 관리", "추가 메모"];
const csvCell = (value: string) => `"${String(value).replaceAll('"', '""')}"`;

export default function Admin() {
  const [responses, setResponses] = useState<SurveyResponse[]>([]);
  const load = () => setResponses(JSON.parse(localStorage.getItem(SURVEY_STORAGE_KEY) || "[]"));
  useEffect(load, []);
  const download = () => {
    const rows = responses.map((item) => [new Date(item.submittedAt).toLocaleString("ko-KR"), item.conditionName, item.name, item.managementStatus, item.biggestChallenge, item.preferredCare, item.note]);
    const csv = "\uFEFF" + [headers, ...rows].map((row) => row.map(csvCell).join(",")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = `care-t-survey-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url);
  };
  const clear = () => { if (window.confirm("현재 브라우저에 저장된 설문 데이터를 모두 삭제할까요?")) { localStorage.removeItem(SURVEY_STORAGE_KEY); load(); } };
  return <div className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 sm:py-10"><main className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><button onClick={() => { window.location.href = "/"; }} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-bold text-slate-700 hover:bg-white"><ArrowLeft className="h-5 w-5" />메인으로</button><div className="flex gap-2"><button onClick={load} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 hover:border-teal-300"><RefreshCw className="h-4 w-4" />새로고침</button><button onClick={download} disabled={!responses.length} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-teal-600 px-4 text-sm font-extrabold text-white shadow-sm hover:bg-teal-700 disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-4 w-4" />엑셀 다운로드</button></div></div><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2 text-teal-700"><FileSpreadsheet className="h-5 w-5" /><span className="text-xs font-extrabold tracking-wider">CARE-T ADMIN</span></div><h1 className="mt-2 text-2xl font-extrabold text-slate-900">건강설문 응답 데이터</h1><p className="mt-1 text-sm text-slate-500">현재 브라우저에 저장된 응답 {responses.length}건을 조회합니다.</p></div>{responses.length > 0 && <button onClick={clear} className="inline-flex items-center gap-2 text-xs font-bold text-rose-600 hover:underline"><Trash2 className="h-4 w-4" />전체 삭제</button>}</div><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[920px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-600"><tr>{headers.map((header) => <th key={header} className="px-3 py-3 font-extrabold">{header}</th>)}</tr></thead><tbody>{responses.length ? responses.map((item) => <tr key={item.id} className="border-t border-slate-100 align-top"><td className="whitespace-nowrap px-3 py-3">{new Date(item.submittedAt).toLocaleString("ko-KR")}</td><td className="px-3 py-3 font-bold text-teal-700">{item.conditionName}</td><td className="px-3 py-3">{item.name}</td><td className="px-3 py-3">{item.managementStatus}</td><td className="max-w-xs px-3 py-3 leading-relaxed">{item.biggestChallenge}</td><td className="px-3 py-3">{item.preferredCare}</td><td className="max-w-xs px-3 py-3 leading-relaxed">{item.note || "—"}</td></tr>) : <tr><td colSpan={headers.length} className="px-5 py-16 text-center text-slate-400">아직 제출된 설문이 없습니다.</td></tr>}</tbody></table></div><p className="mt-4 text-xs leading-relaxed text-slate-400">현재는 브라우저 로컬 저장 기반 프로토타입입니다. 여러 사용자 기기에서 공유되는 운영용 데이터 저장은 서버 DB 연결이 필요합니다.</p></section></main></div>;
}
